import { DateTracking } from './../../shared/models/date-tracking.model';
import { DateTime } from './../../shared/models/datetime.model';
import { IEvent, Event } from './../../shared/models/event.model';

export const upcomingEventData = [
  new Event({
    name: 'This is event A',
    place: 'Building 1',
    date: '14/05/2019',
    time: '14:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 0,
  }),
  new Event({
    name: 'This is event B',
    place: 'Building 2',
    date: '14/05/2019',
    time: '10:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 1,
  }),
  new Event({
    name: 'This is event C',
    place: 'Building 3',
    date: '14/05/2019',
    time: '16:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 3,
  }),
  new Event({
    name: 'This is event D',
    place: 'Building 4',
    date: '14/05/2019',
    time: '14:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 2,
  }),
  new Event({
    name: 'This is event E',
    place: 'Building 5',
    date: '14/05/2019',
    time: '16:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 4,
  }),
  new Event({
    name: 'This is event F',
    place: 'Building 6',
    date: '14/05/2019',
    time: '09:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 0,
  }),
  new Event({
    name: 'This is event G',
    place: 'Building 7',
    date: '14/05/2019',
    time: '14:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 0,
  }),
  new Event({
    name: 'This is event H',
    place: 'Building 8',
    date: '14/05/2019',
    time: '14:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 0,
  }),
  new Event({
    name: 'This is event I',
    place: 'Building 9',
    date: '14/05/2019',
    time: '14:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 0,
  }),
  new Event({
    name: 'This is event J',
    place: 'Building 10',
    date: '14/05/2019',
    time: '14:00',
    price: 10,
    capacity: 40,
    amount: 15,
    discount: 10,
    promotionCode: ['QWE', 'ZXC', 'ASD'],
    status: 0,
  })
]
